;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        capitalize-dwim
        evilnc-comment-or-uncomment-lines
        hs-hide-level
        indent-for-tab-command
        keyboard-escape-quit
        move-text-up
        my/backward-delete-word
        my/kill-line-or-region
        ns-copy-including-secondary
        org-beginning-of-line
        org-end-of-line
        org-return-and-maybe-indent
        org-self-insert-command
        org-yank
        pixel-scroll-precision
        upcase-char
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        consult-buffer
        org-cycle
        ))
